### ISSUE TITLE
Callouts

### ISSUE THREAD

**Issue by matthiasbaitsch** [leovan/quarto-style-text#2]
On my mac, the style-text filter breaks pdf output for a callout note (Quarto version 1.4.551), example below. 

```{markdown}
---
title: "Test Text Styling"
filters: 
  - style-text
format:
    pdf: default
---

::: {.callout-note}

Hello World!

:::
```

**Comment by leovan** [comment]
It's the problem of filters order. Callout is process by built-in filter `quarto`, you can manually run it first as below. It works for me.

```yaml
---
title: "Test Text Styling"
filters: 
  - quarto
  - style-text
format:
    pdf: default
---

::: {.callout-note}
Hello World!
:::
```
